### ISSUE TITLE
doc: port Wide Range of Snowpal APIs article

### ISSUE THREAD

**Issue by kpalania** [snowpal/API#14]
https://products.snowpal.com/p/range-of-snowpal-apis-to-help-developers?r=375hyn&utm_campaign=post&utm_medium=web

**Comment by vpalania** [comment]
https://github.com/snowpal/backend-as-a-service-api/wiki/A-wide-range-of-Snowpal-APIs-to-allow-developers-to-focus-on-core-customer-problems
