### ISSUE TITLE
doc: port domain-agnostic APIs article

### ISSUE THREAD

**Issue by kpalania** [snowpal/API#16]
https://products.snowpal.com/p/industry-agnostic-feature-rich-stable-apis?r=375hyn&utm_campaign=post&utm_medium=web

**Comment by vpalania** [comment]
https://github.com/snowpal/backend-as-a-service-api/wiki/Industry%E2%80%90agnostic,-Feature%E2%80%90rich,-Stable-Snowpal-APIs-to-expedite-Time-to-Market
