### ISSUE TITLE
doc: port Do not reinvent the wheel article

### ISSUE THREAD

**Issue by kpalania** [snowpal/API#20]
https://products.snowpal.com/p/do-not-reinvent-the-wheel-and-waste-time?r=375hyn&utm_campaign=post&utm_medium=web

**Comment by vpalania** [comment]
https://github.com/snowpal/backend-as-a-service-api/wiki/Reinventing-the-wheel-is-an-expensive-proposition.-Integrate-Snowpal-APIs-to-go-to-market-sooner.
