### ISSUE TITLE
doc: port Video Release to reduce Time to Market article

### ISSUE THREAD

**Issue by kpalania** [snowpal/API#21]
https://products.snowpal.com/p/integrating-apis-to-reduce-time-to-market?r=375hyn&utm_campaign=post&utm_medium=web

**Comment by vpalania** [comment]
https://github.com/snowpal/backend-as-a-service-api/wiki/Integrating-Snowpal-APIs-to-reduce-Time-to-Market:-Announcing-Video-Releases
