### ISSUE TITLE
doc: port Integrate API to save time article

### ISSUE THREAD

**Issue by kpalania** [snowpal/API#38]
https://products.snowpal.com/p/use-snowpal-apis-to-save-time

**Comment by vpalania** [comment]
https://products.snowpal.com/p/use-snowpal-apis-to-save-time

**Comment by vpalania** [comment]
https://github.com/snowpal/backend-as-a-service-api/wiki/Backend-as-a-Service:-Use-Snowpal-APIs-to-save-money-(and-time)
